interactions:
- request:
    body: ''
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-type:
      - application/json
      host:
      - api.openai.com
      user-agent:
      - OpenAI/Python 1.30.1
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 1.30.1
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.5
    method: GET
    uri: https://api.openai.com/v1/models/gpt-4o-foo
  response:
    body:
      string: "{\n  \"error\": {\n    \"message\": \"The model 'gpt-4o-foo' does not
        exist\",\n    \"type\": \"invalid_request_error\",\n    \"param\": \"model\",\n
        \   \"code\": \"model_not_found\"\n  }\n}\n"
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 887d0225efd37fa9-MAA
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Wed, 22 May 2024 13:03:48 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      access-control-allow-origin:
      - '*'
      alt-svc:
      - h3=":443"; ma=86400
      content-length:
      - '166'
      openai-processing-ms:
      - '63'
      openai-version:
      - '2020-10-01'
      strict-transport-security:
      - max-age=15724800; includeSubDomains
      x-request-id:
      - req_ec3916854d4354fb42d4d1e8fa68bc88
    status:
      code: 404
      message: Not Found
version: 1
