interactions:
- request:
    body: ''
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-type:
      - application/json
      host:
      - api.openai.com
      user-agent:
      - AsyncOpenAI/Python 1.30.1
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - async:asyncio
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 1.30.1
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.5
    method: GET
    uri: https://api.openai.com/v1/models/gpt-4o-foo
  response:
    body:
      string: "{\n  \"error\": {\n    \"message\": \"The model 'gpt-4o-foo' does not
        exist\",\n    \"type\": \"invalid_request_error\",\n    \"param\": \"model\",\n
        \   \"code\": \"model_not_found\"\n  }\n}\n"
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 887daf81ce9e7f84-MAA
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Wed, 22 May 2024 15:02:09 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      access-control-allow-origin:
      - '*'
      alt-svc:
      - h3=":443"; ma=86400
      content-length:
      - '166'
      openai-processing-ms:
      - '36'
      openai-version:
      - '2020-10-01'
      strict-transport-security:
      - max-age=15724800; includeSubDomains
      x-request-id:
      - req_8e2f2d769db9b3c419e22a20b2c7998b
    status:
      code: 404
      message: Not Found
version: 1
